In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib_venn import venn2
import pandas_datareader
import datetime
import os
os.listdir('./Data/')

['.ipynb_checkpoints', 'EducationDATA.xlsx', 'GDPDATA.xlsx', 'opgave1.ipynb']

In [23]:
GDP = 'data/GDPDATA.xlsx'
EDU = 'data/EducationDATA.xlsx'

In [25]:
pd.read_excel(EDU)

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,Last Updated Date,2019-03-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.00000,2017.00000,2018.0
3,Aruba,ABW,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.924790,6.929270,6.119130,6.549060,6.808060,6.162930,6.479060,NaN,NaN,NaN
4,Afghanistan,AFG,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.461960,3.437850,2.524410,3.434370,3.673900,3.242020,4.20525,3.92675,NaN
5,Angola,AGO,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.474110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Albania,ALB,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.539300,NaN,3.437970,3.95464,2.18972,NaN
7,Andorra,AND,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.154840,3.057420,3.145080,NaN,2.438070,2.997810,3.253680,3.25670,3.19556,NaN
8,Arab World,ARB,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,United Arab Emirates,ARE,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Argentina,ARG,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.531050,5.019710,5.290630,5.345830,5.436610,5.361440,5.776110,5.57218,NaN,NaN
11,Armenia,ARM,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.840790,3.249000,3.143850,2.772480,2.650180,2.247240,2.805910,2.75812,NaN,NaN
12,American Samoa,ASM,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Antigua and Barbuda,ATG,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.517240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Australia,AUS,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.093270,5.559170,5.083130,4.877650,5.238010,5.173680,5.321750,NaN,NaN,NaN
15,Austria,AUT,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.730250,5.700480,5.592270,5.480400,5.547110,5.448980,5.453040,NaN,NaN,NaN
16,Azerbaijan,AZE,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.224310,2.780620,2.435640,2.067630,2.442130,2.633040,2.951680,2.90341,NaN,NaN
17,Burundi,BDI,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.319790,6.792870,5.997790,5.820910,5.414750,5.933910,6.448810,4.61813,4.34407,NaN
18,Belgium,BEL,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.638980,6.552380,NaN,NaN,NaN
19,Benin,BEN,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.222040,5.029320,NaN,4.868160,4.547320,4.321130,4.356430,3.99469,NaN,NaN
20,Burkina Faso,BFA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.938960,4.483260,4.053530,4.593840,4.559940,4.166070,NaN,NaN,NaN
21,Bangladesh,BGD,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.939420,NaN,2.132700,2.175500,1.966160,NaN,NaN,1.53554,NaN,NaN
22,Bulgaria,BGR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.285750,3.863460,3.563030,3.502030,4.061970,NaN,NaN,NaN,NaN,NaN
23,Bahrain,BHR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.645310,2.476880,2.467460,2.668080,2.66671,NaN,NaN
24,"Bahamas, The",BHS,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Bosnia and Herzegovina,BIH,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Belarus,BLR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.516720,5.220040,4.684790,4.959640,5.009420,4.818310,4.787520,4.94655,4.82003,NaN
27,Belize,BLZ,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100140,6.621000,NaN,NaN,6.218060,6.478660,6.722520,7.06045,7.08741,NaN
28,Bermuda,BMU,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.586090,2.585200,NaN,NaN,NaN,1.752550,1.689730,NaN,1.49201,NaN
29,Bolivia,BOL,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.081200,7.600110,6.888470,6.425240,6.257930,7.285350,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.325745,4.666795,4.726890,5.033070,5.004640,5.260990,4.936200,4.52064,NaN,NaN
238,Timor-Leste,TLS,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.931440,2.449550,1.870330,1.245990,1.399810,2.688800,NaN,NaN,NaN,NaN
239,Middle East & North Africa (IDA & IBRD countries),TMN,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,Tonga,TON,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,South Asia (IDA & IBRD),TSA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.590780,3.423470,2.829800,2.349955,2.963905,3.069915,2.946020,3.47508,3.36707,NaN
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.079705,3.836175,3.925110,4.101180,4.057170,4.313300,4.561470,NaN,NaN,NaN
243,Trinidad and Tobago,TTO,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Tunisia,TUN,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.528480,6.254810,NaN,6.250370,NaN,NaN,6.598570,NaN,NaN,NaN
245,Turkey,TUR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.419000,4.364100,4.371160,4.291870,NaN,NaN,NaN
246,Tuvalu,TUV,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Tanzania,TZA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.043650,4.622390,NaN,NaN,NaN,3.481430,NaN,NaN,NaN,NaN
248,Uganda,UGA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.389010,3.037670,2.483140,2.208760,2.250680,2.773760,2.55882,2.64100,NaN
249,Ukraine,UKR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.310880,NaN,6.162370,6.692330,6.671660,5.874940,NaN,5.01437,NaN,NaN
250,Upper middle income,UMC,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.516720,4.185445,4.476395,4.385310,4.124020,4.518160,4.291870,NaN,NaN,NaN
251,Uruguay,URY,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.355270,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,United States,USA,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.420010,5.223900,5.194860,4.943790,4.989480,NaN,NaN,NaN,NaN
253,Uzbekistan,UZB,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.283540,7.318660,7.078820,6.91097,6.41335,NaN
254,St. Vincent and the Grenadines,VCT,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.689780,5.085230,NaN,NaN,NaN,NaN,NaN,5.79986,5.75045,NaN
255,"Venezuela, RB",VEN,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.874670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,British Virgin Islands,VGB,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.050740,4.447750,NaN,NaN,NaN,NaN,6.317280,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Vietnam,VNM,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.816500,5.137220,4.813720,5.533290,5.652000,NaN,NaN,NaN,NaN,NaN
259,Vanuatu,VUT,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.012950,NaN,NaN,NaN,NaN,4.910830,5.549870,NaN,4.69537,NaN
260,World,WLD,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.669830,4.570005,4.483260,4.536710,4.683260,4.722515,4.813975,NaN,NaN,NaN
261,Samoa,WSM,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.08105,NaN,NaN
262,Kosovo,XKX,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,South Africa,ZAF,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.248690,5.721740,5.962750,6.371640,6.013540,6.046620,5.956190,5.94059,6.12535,NaN
265,Zambia,ZMB,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zimbabwe,ZWE,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.833290,NaN,7.294430,7.408170,7.530680,NaN,NaN,NaN,NaN